/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stdint.h"
#pragma pack(1)

typedef volatile unsigned int vuint32_t ;

#define RCC_BASE	 0x40021000
#define GPIOA_BASE	 0x40010800

#define APB2ENR_R	 *((vuint32_t*)(RCC_BASE + 0x18))
#define GPIOA_CRH	 *((vuint32_t*)(GPIOA_BASE + 0x04))
#define GPIOA_ODR	 *((vuint32_t*)(GPIOA_BASE + 0x0c))

typedef union {
    vuint32_t   all_fields;
    struct{
    vuint32_t   reserved:13;
    vuint32_t   pin_13:1;
    }Pin;
}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(GPIOA_BASE + 0x0c);
unsigned char g_variables[3] = {1,2,3};
unsigned const char const_variables[3] = {1,2,3};
unsigned char bss_var [3];

extern void Bus_Fault()
{

}

extern void MM_Fault()
{

}

int main(void)
{
	int i;
		APB2ENR_R  |= 	(1<<2);
		GPIOA_CRH  &=	 0xFF0FFFFF;
		GPIOA_CRH  |=	 0x00200000;

		while(1){
			GPIOA_ODR ^= (1<<13);
			for(i=0; i<30000; i++);
	//		GPIOA_ODR &=~ (1<<13);

		}

	    return 0;
}
